version: '3'

services:
  server:
    entrypoint: 
      - "./wait-for-it.sh"
      - "${RBMQ_HOST}:${RBMQ_PORT}"
      - "--"
      - "./wait-for-it.sh"
      - "${MYSQL_HOST}:${MYSQL_PORT}"
      - "--"
      - "go"
      - "run"
      - "./cmd/server/main.go"

  consumer:
    entrypoint: 
      - "./wait-for-it.sh"
      - "${RBMQ_HOST}:${RBMQ_PORT}"
      - "--"
      - "./wait-for-it.sh"
      - "${MYSQL_HOST}:${MYSQL_PORT}"
      - "--"
      - "go"
      - "run"
      - "./cmd/consumer/main.go"

  migrator:
    entrypoint:
      - "./wait-for-it.sh"
      - "${MYSQL_HOST}:${MYSQL_PORT}"
      - "--"
      - "go"
      - "run"
      - "./cmd/migrator/main.go"

  swagger:
    hostname: mailer-swagger
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yaml

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - server
      - rabbitmq
      - swagger

  mysql:
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
